---
title: "Gene set expression analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Gene set expression analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
set.seed(123)
library("GimmeMyOmics")
library("clusterProfiler")
library("enrichplot")
# source("R/utils_enrich.R")
# source("R/utils_network.R")
method <- "gsea"
label_x <- "NES"
org_lib <- "org.Hs.eg.db"
org <- "hsa"
# org_lib <- "org.Mm.eg.db"
# org <- "mmu"
# method <- "kegg"
# label_x <- "generatio"
library(org_lib, character.only = TRUE)
select <- dplyr::select
```

# Data preparation
```{r, eval=FALSE}
# metric <- "pfc"
# metric <- "ranked_padj"
metric <- "log2FoldChange"
de_genes_ranked <- top_genes(dea_pretty, 0.01, 1, n = 50000, return_rank = TRUE) %>%
    # mutate(ranked_padj = sign(log2FoldChange) * (log10(padj))) %>%
    pull(metric, name = ensembl_gene_id) %>%
        sort(decreasing = TRUE) %>%
        .[!is.na(names(.))] %>%
        .[is.finite(.)]
length(de_genes_ranked)
```

# GSEA
```{r, eval=FALSE}
enrichment <- gseGO(
      de_genes_ranked,
      # universe = names(de_genes_ranked),
      ont = "ALL",
      OrgDb = get(org_lib),
      keyType = "ENSEMBL",
      verbose = FALSE
      ) %>%
      setReadable(org_lib, 'ENSEMBL') %>%
    suppressWarnings() %>%
    invisible()

use_data(enrichment, overwrite = TRUE)
# saveRDS(enrichment, file = file.path(path, paste0("gse_go", project_name, ".RDS")))
# enrichment <- readRDS(file.path(path, paste0("gse_go", project_name, ".RDS")))
```

# ORA
## Enrichr
```{r, eval=FALSE}
library("enrichR")
setEnrichrSite("Enrichr")
dbs <- c("GO_Molecular_Function_2025", "GO_Biological_Process_2025",
         "Orphanet_Augmented_2021", "WikiPathway_2024_Human", 
         "MSigDB_Hallmark_2020", "Reactome_2022")

dbs <- listEnrichrDbs()
mouse_dbs <- dbs[grep("Mouse|MGI|mmusculus", dbs$libraryName, ignore.case = TRUE), ]
mouse_dbs$Year <- as.numeric(str_extract(mouse_dbs$libraryName, "20\\d{2}"))
mouse_dbs$BaseName <- trimws(gsub("20\\d{2}", "", mouse_dbs$libraryName)) %>% str_remove("_$")
dbs <- mouse_dbs %>%
  group_by(BaseName) %>%
  filter(is.na(Year) | Year == max(Year, na.rm = TRUE)) %>%
  ungroup() %>%
  pull(libraryName)

deg <- top_genes(dea_pretty, log2(1.5), 0.1)
l_enrichment <- enrichr(deg, dbs)#,  background = pull(dea_pretty, "gene_name"))

plot_enrich(l_enrichment[[1]], method = "enrichr")
```
## ClusterprofilR
```{r, eval=FALSE}
# deg <- filter(deg0, cluster == 6) %>% ungroup() %>% pull(gene)
deg <- top_genes(dea_pretty, log2(1.5), 0.1)
deg_entrez <- deg %>% bitr("ALIAS", "ENTREZID", org_lib) %>% pull(2)

TERM2GENE <- term2gene_enrichr("Mouse_Gene_Atlas")
# func <- enrichKEGG
func <- enricher

enrichment <- func(
  deg_entrez,
  TERM2GENE = TERM2GENE,
  pvalueCutoff = 1,
  qvalueCutoff = 1,
  organism = org,
  # organism = "Mus musculus"
  # OrgDb = get(org_lib),
  # universe = pull(dea_pretty, "gene_name")
)  %>%
      setReadable(org_lib, 'ENTREZID')

path2code_kegg <- read_tsv("https://rest.kegg.jp/list/pathway/mmu", FALSE)  %>%
  mutate(X1 = str_remove_all(X1, ".*\\:"))
```


# All pathways
```{r}
data("gse_go")
enrichment <- gse_go
plot_enrich(enrichment, method = method, label_x = label_x)# + 
# scale_fill_gradientn(
#     labels = function(x) label_pvalue()(x),
#     breaks = c(0.002, 0.001, 0),
#     name = "FDR",
#     limits = c(0, 0.003),
#     colours = c(palette_discrete()[1], "gray50", palette_discrete()[2])
# ) +
#     scale_size_continuous(
#         range = c(5, 12) * 0.6,
#         breaks = c(50, 100, 150, 200, 250),
#         labels = scales::label_number(accuracy = 1),
#         name = "# Leading genes",
#         limits = c(10, 300)
#     )
(table_gsea <- print_enrich(enrichment, method = method))
```

# Targeting all immunity 
```{r, message = FALSE}
plot_enrich(enrichment, label_x = label_x, method = method, regex = pathway_keywords()$immunity_full)
print_enrich(enrichment, method = method, regex = pathway_keywords()$immunity_full)
```

# Targeting only cytokines
```{r}
plot_enrich(enrichment, label_x = label_x, method = method, regex = pathway_keywords()$immunity)
plot_enrich(enrichment, label_x = label_x, method = method, regex = pathway_keywords()$cytokine_full, n = 25)
print_enrich(enrichment, method = method, regex = pathway_keywords()$cytokine_full)
```

# Targeting only cell processes
```{r, eval = FALSE}
plot_enrich(enrichment, label_x = label_x, method = method, regex = pathway_keywords()$cell)
print_enrich(enrichment, method = method, regex = pathway_keywords()$cell)
```

# Targeting a specific pathway
```{r}
data("dea_pretty")
(targeted_paths <- print_enrich(enrichment, method = method, regex = "eutrophil activation"))
gene_path <- targeted_paths %>%
    select(Genes) %>% 
    map(~ str_split(., ";") %>% unlist() %>% sort()) %>% 
    pluck(1)

dea_path <- filter(dea_pretty, gene_name %in% gene_path)
```


```{r, eval = FALSE}
data("dea")
count_normalized <- vst(dea, blind = FALSE)
plot_heatmap(dea_path, metadata_samples, count_normalized, cutree_cols = 2)
```


```{r}
fc_threshold <- log2(1.5)
p_threshold <- .05
top_genes <- top_genes(
    dea_pretty,
     fc_threshold = fc_threshold,
     p = p_threshold,
     n = 15
   )
top_markers <- pull(top_genes, "gene_name") %>% sort()
intersect(gene_path, top_markers)

top_path_genes <- filter(dea_pretty, gene_name %in% gene_path) %>%
    top_genes(
     fc_threshold = 0,
     p = 1,
     n = 15
   )
volcano_plot(
      dea_pretty,
      top_genes = top_path_genes,
      cex = 1,
      legend = "none",
      fc_threshold = fc_threshold,
      p_threshold = p_threshold
    ) + xlab("") + ylab("")
```

```{r, eval = FALSE}
count_normalized <- vst(dea, blind = FALSE)

extract_normalized_genes <- function(x, count_normalized, metadata_samples) {
    assay(count_normalized)[pull(x, "ensembl_gene_id"), ] %>%
    set_colnames(pull(metadata_samples, 1)) %>%
    set_rownames(pull(x, gene_name))
}
targeted_genes <- extract_normalized_genes(dea_path, count_normalized, metadata_samples)
sampleDists <- dist(t(targeted_genes))
  
top_cluster_genes <- getDiscriminantVariables(
    t(targeted_genes), 
    hclust(sampleDists) %>% cutree(2),
    n_cluster = 2
)
select(top_cluster_genes, 1) %>%
    plot_bar(
        colour = brewer.pal(7, "Reds") %>% rev() %>% .[-7],
        sample_size = 100,
        digits = 1
    )

gene <- filter(dea_pretty, gene_name == rownames(top_cluster_genes)[1])

conditions <- dea@design %>%
  as.character() %>%
  .[2] %>% 
  str_split("[+:]") %>%
  unlist() %>%
  str_trim() %>%
  unique()
gene_per_sample <- plotCounts(
    dea,
    pull(gene, "ensembl_gene_id"),
    intgroup = conditions[-3],
    returnData = TRUE
)

var_group <- "condition"
list.map(
    pull(gene_per_sample, !!sym(var_group)) %>% unique(), 
    f(x) ~filter(gene_per_sample, !!sym(var_group) == x) %>% select(count)
) %>%
    list_cbind0() %>% 
    set_colnames(pull(gene_per_sample, !!sym(var_group)) %>% unique()) %>%
    plot_violin(
        pch_size = 4,
        display_log = TRUE,
        # breaks = c(250, 500, 1e3),
        title = pull(gene, "gene_name")
    ) %>% suppressMessages()
```

# Multiple related pathways
```{r, eval = FALSE}
(targeted_paths <- print_enrich(enrichment, method = method, regex = "eutrophil"))
l_path <- list.map(
    pull(targeted_paths, Description), 
    f(i) ~ filter(targeted_paths, Description == i) %>%
        pull(Genes) %>%
        str_split(";") %>%
        pluck(1) %>%
        sort()
    ) %>% set_names(names(.) %>% format_path(100))
gene_path <- unlist(l_path) %>% unique() %>% sort()

filter(dea_pretty, `gene_name` %in% gene_path) %>% 
    plot_heatmap(metadata_samples, count_normalized, cutree_cols = 2)
```

```{r, eval = FALSE}
gene_ont <- "gene_name"
gene_path <- list_table(l_path) %>% rownames()
gene_path0 <- #l_de2[[1]] %>%
  dea_pretty %>%
  filter(str_detect(!!sym(gene_ont), paste0("^", gene_path, "$", collapse = "|"))) %>% 
  top_genes(1e-9, 1, return_rank = TRUE) %>%
  mutate(pfc = -pfc)
gene_path1 <- gene_path0 %>% 
  filter(!duplicated(!!sym(gene_ont))) %>% 
  set_rownames(pull(., gene_ont)) %>% 
  select(log2FoldChange) %>% 
  set_colnames("value2") %>% 
  rownames_to_column("ID")

common_genes <- list_count(l_path) %>% unlist() %>% unname()

list_count(l_path) %>%
    list.map(
        f(i, j, k) ~unlist(i) %>%
            unname() %>% 
            rep(., k)
    ) %>%
    unlist() %>%
    plot_bar_mcat(
        n_max = 6,
        sample_size = length(l_path),
        collapse = TRUE,
        colour_gradient = brewer.pal(7, "Reds") %>% .[-7]
    ) + 
    theme(axis.ticks.y = element_blank(), panel.border = element_blank())

# list_table(l_path) %>% heatmap_enrich(1.25, 100)
list.map(l_path, f(i) ~i %>% .[. %in% common_genes]) %>%
    list_table() %>% 
    select(colnames(.) %>% sort()) %>%
    heatmap_enrich(1.25, 100)
```

# Pathway network
```{r}
enrichment2 <- filter_gsea(
    enrichment, 
    regex = pathway_keywords()$cellcycle,
    negate = TRUE
  ) %>%
  filter_gsea(regex = pathway_keywords()$immunity_full) %>%
  pairwise_termsim() %>% 
  clusterProfiler::simplify(cutoff = 0.9)
```

```{r}
map_enrich(
    enrichment2,
    cluster.params = list(cluster = FALSE),
    regex = pathway_keywords()$immunity_additional,
    showCategory = 50,
    cex.params = list(category_label =  0.9, line = 0.5),
    cex = 0.7
) %>% suppressMessages()
```

```{r, eval = FALSE}
tree_enrich(
    enrichment2,
    regex = pathway_keywords()$immunity,
    showCategory = 50,
    verbose = FALSE,
    label_words_n = 2,
    width = 100
) %>% suppressMessages()
```

```{r}
network_enrich(
    enrichment2,
    foldChange = enrichment2@geneList,
    regex = pathway_keywords()$cell,
    showCategory = 20,
    col_highlight = brewer.pal(8, "Reds") %>% rev(),
    cex = 0.5
) %>% suppressMessages()
```

```{r, eval = FALSE}
ridge_gsea(
    enrichment2,
    regex = pathway_keywords()$cell,
    width = 100
) %>% suppressMessages()
```

```{r}
gsea_enrich(
    enrichment2,
    regex = "eutrophil",
    geneSetID = seq(3),
    title = "Neutrophil activity"
)
gsea_enrich(enrichment2, regex = "eutrophil", width = 100)
```

```{r}
sessionInfo()
```
